### ISSUE TITLE
LDAP_INIT_PPOLICY_DEFAULT_DN enviroment variable does not work as documented

### ISSUE THREAD

**Issue by aimoff** [vegardit/docker-openldap#11]
Current `dn` definition of default password policy in `image/ldifs/init_org_ppolicy.ldif` is:
```
dn: cn=DefaultPasswordPolicy,ou=Policies,${LDAP_INIT_ORG_DN}
```
Thus `LDAP_INIT_PPOLICY_DEFAULT_DN` doesn't work.
Following line is suitable.
```
dn: ${LDAP_INIT_PPOLICY_DEFAULT_DN:-cn=DefaultPasswordPolicy,ou=Policies,${LDAP_INIT_ORG_DN}}
```
I tried to mount customized ldif file at `/opt/ldifs/init_org_ppolicy.ldif`, and it works.

**Comment by sebthom** [comment]
Thanks for reporting!
