### ISSUE TITLE
Failed to initialize organization object

### ISSUE THREAD

**Issue by aimoff** [vegardit/docker-openldap#12]
Current initial ldif for organization (in `init_org_tree.ldif`) is:
```
dn: ${LDAP_INIT_ORG_DN}
description: ${LDAP_INIT_ORG_NAME}
objectClass: top
objectClass: organization
${LDAP_INIT_ORG_DN_ATTR}
```
The `LDAP_INIT_ORG_DN_ATTR` is substitued by `run.sh` as:
```
   LDAP_INIT_ORG_DN_ATTR=$(substr_before $LDAP_INIT_ORG_DN "," | str_replace "=" ": ") # referenced by init_org_tree.ldif
```
Most of cases, `LDAP_INIT_ORG_DN` is `dc=xxxxx,dc=yyy` format.
The `LDAP_INIT_ORG_DN_ATTR` is substituted to `dc: xxxxx`, but `organization` object class MUST have `o` attribute. The container is failed to initialize and restarted.

**Comment by sebthom** [comment]
the o attribute is now derived from the LDAP_INIT_ORG_DN:
```
LDAP_INIT_ORG_DN="O=example.com"               -> LDAP_INIT_ORG_ATTR_O="example.com"
LDAP_INIT_ORG_DN="O=Example,DC=example,DC=com" -> LDAP_INIT_ORG_ATTR_O="Example"
LDAP_INIT_ORG_DN="DC=example,DC=com"           -> LDAP_INIT_ORG_ATTR_O="example.com"
```

or you can manually set it via LDAP_INIT_ORG_ATTR_O. See https://github.com/vegardit/docker-openldap/commit/1fe0ba015a5b73fdfb3ff01c96fa0288da447685

**Comment by aimoff** [comment]
Two issues still exist.

The one is simple.
`example/docker-compose/ldifs/init_org_tree.ldif` was revised, but `image/ldifs/init_org_tree.ldif` is still old.

The other one is complecated.
When `LDAP_INIT_ORG_DN` is `DC=example,DC=com` format, `dcObject` class is also required.
Thus, the `run.sh` script has to be modified such as:
```sh
   if [[ -z "${LDAP_INIT_ORG_DN_ATTR}" ]]; then
     if [[ "$LDAP_INIT_ORG_DN" =~ [oO]=([^,]*) ]]; then # check if "o=..." attribute is present in DN
       # e.g. LDAP_INIT_ORG_DN="O=example.com"               -> LDAP_INIT_ORG_ATTR_O="example.com"
       # e.g. LDAP_INIT_ORG_DN="O=Example,DC=example,DC=com" -> LDAP_INIT_ORG_ATTR_O="Example"
       LDAP_INIT_ORG_DN_ATTR="o: ${BASH_REMATCH[1]}"
     elif [[ "${LDAP_INIT_ORG_DN}" =~ [dD][cC]=([^,]*) ]]; then
       # e.g. LDAP_INIT_ORG_DN="DC=example,DC=com" -> LDAP_INIT_ORG_ATTR_O="example.com"
       LDAP_INIT_ORG_DN_ATTR="objectClass: dcObject
o: $(echo $LDAP_INIT_ORG_DN | grep -ioP 'DC=\K[^,]+' | paste -sd '.')
dc: ${BASH_REMATCH[1]}"
     else
```
This reverts `init_org_tree.ldif` to previous one.
It works fine, but the mechanism is complex and unintuitive.

**Comment by sebthom** [comment]
@aimoff is it working for you now?

**Comment by aimoff** [comment]
Thanks for your efforts.
I'm sorry, but I already switched the openldap image base to another one.
I forgot the reason. Probably, the initial LDAP database structure is not compatible with a LDAP management tool that I want to use.
