### ISSUE TITLE
LDAP_INIT_RFC2307BIS_SCHEMA="1" - ldapdelete fails on initialize

### ISSUE THREAD

**Issue by yella-canary** [vegardit/docker-openldap#4]
Hi. 
Thank you for making this repo/image available!
Hoping you may be able to help with an issue.

I am trying to initialize a container with LDAP_INIT_RFC2307BIS_SCHEMA set to  '1'.

The ldapdelete command on line 122 in run.sh fails on initialization with:

```
INFO [/opt/run.sh:121] Replacing NIS (RFC2307) schema with RFC2307bis schema...
SASL/EXTERNAL authentication started
ldap_sasl_interactive_bind: Unknown authentication method (-6)
        additional info: SASL(-4): no mechanism available: 
Error - exited with status 250 in [/opt/run.sh] at line 122:
```

I believe I have all the required environment variables set in my docker-compose file.

If I try to start(init) a new container with LDAP_INIT_RFC2307BIS_SCHEMA set to "0" there is no problem, everything works.

I need to use RFC2307BIS as it meets some specific requirements (member attribute in groups).
Have you successfully initialized a container with this attribute set to 1?

Any ideas or suggestions really, really appreciated.

yElla .

**Comment by sebthom** [comment]
I am relatively sure this used to work with openldap 2.4 before. Anyways I did some research and found that deleting an existing schema using ldapmodify is/was supported only experimentally (in our case the `nis` schema) and apparently isn't possible with openldap 2.5 or at least not with the version provided by debian. so far I couldn't find any way how to replace the `nis` schema with the `bis` schema in openldap 2.5. If you can find some working instructions I can try to update the init script accordingly.

**Comment by yella-canary** [comment]
Hi. Thank you for the reply. I have made a fork and am testing some ideas. I think it can all be done within run.sh, with some text wrangling. I'll submit a PR for review when I have something to share.

**Comment by sebthom** [comment]
Fixed with https://github.com/vegardit/docker-openldap/commit/9aa1fd73ccc47459c43a209412c77a1d06172e7d
